[tool.poetry]
name = "The Dynamic Typists"
version = "0.1.0"
description = ""
authors = ["Author 1 <email@mail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.11.*"

[tool.poetry.dev-dependencies]
isort = "~5.12.0"
pre-commit = "~3.3.3"
ruff = "~0.0.286"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
