# GitHub Action Workflow enforcing our code style.

name: Lint

# Trigger the workflow on both push (to the main repository, on the main branch)
# and pull requests (against the main repository, but from any repo, from any branch).
on:
  push:
    branches:
      - main
  pull_request:
# Brand new concurrency setting! This ensures that not more than one run can be triggered for the same commit.
# It is useful for pull requests coming from the main repository since both triggers will match.
concurrency: lint-${{ github.sha }}

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      # The Python version your project uses. Feel free to change this if required.
      PYTHON_VERSION: "3.11"

    steps:
      # Checks out the repository in the current folder.
      - name: Checks out repository
        uses: actions/checkout@v3

      # Set up the right version of Python
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install poetry==1.6.1; poetry config virtualenvs.create false; poetry install

      - name: Set up pyright
        run: echo "PYRIGHT_VERSION=$(python -c 'import pyright; print(pyright.__pyright_version__)')" >> $GITHUB_ENV

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0

      - name: Type checking
        uses: jakebailey/pyright-action@v1.2.0
        with:
          version: ${{ env.PYRIGHT_VERSION }}
          python-version: ${{ env.PYTHON_VERSION }}
          warnings: true
